fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .plugin(
                "fetch-plugin",
                tauri_build::InlinedPlugin::new().commands(&[
                    "fetch",
                    "fetch_cancel",
                    "fetch_send",
                    "fetch_read_body",
                    "fetch_and_save",
                ]),
            )
            .plugin(
                "proxy-plugin",
                tauri_build::InlinedPlugin::new().commands(&[
                    "get_m3u8_url",
                    "get_proxy_url",
                    "start_cast_proxy_server",
                    "stop_cast_proxy_server",
                    "get_cast_m3u8_url",
                    "get_cast_proxy_url",
                ]),
            )
            .plugin(
                "websocket-plugin",
                tauri_build::InlinedPlugin::new().commands(&["connect", "send"]),
            )
            .plugin(
                "download-manager",
                tauri_build::InlinedPlugin::new().commands(&[
                    "get_tasks",
                    "add_task",
                    "get_download_dir",
                    "set_download_dir",
                    "append_collection_chunk",
                    "download_remote_chunk",
                    "finalize_collection_download",
                    "pause_task",
                    "resume_task",
                    "remove_task",
                    "mark_task_error",
                    "show_in_folder",
                    "package_to_cbz",
                    "mark_chunk_completed",
                    "update_task_downloaded_size",
                    "download_m3u8_chunk",
                    "check_task_file_exist",
                    "check_path_exists",
                ]),
            ),
    )
    .expect("failed to run tauri-build");
}
