[default]
description = "Default permissions for the download manager plugin"
permissions = [
    "allow-get-tasks",
    "allow-add-task",
    "allow-append-collection-chunk",
    "allow-download-remote-chunk",
    "allow-finalize-collection-download",
    "allow-pause-task",
    "allow-resume-task",
    "allow-remove-task",
    "allow-get-download-dir",
    "allow-set-download-dir",
    "allow-show-in-folder",
    "allow-package-to-cbz",
    "allow-mark-chunk-completed",
    "allow-mark-task-error",
    "allow-update-task-downloaded-size",
    "allow-download-m3u8-chunk",
    "allow-check-task-file-exist",
]

[allow]
http = ['http://*']
https = ['https://*']
