# 可以在这里配置赞助链接
# 取消注释并填写你的账户信息

# GitHub Sponsors
# github: [你的用户名]

# Patreon
# patreon: 你的用户名

# Open Collective
# open_collective: 项目名称

# Ko-fi
# ko_fi: 你的用户名

# 自定义链接
# custom: ["https://你的赞助链接"]
