/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/dialogs/About.vue')['default']
    BookCard: typeof import('./src/components/card/BookCard.vue')['default']
    BookShelfButton: typeof import('./src/components/BookShelfButton.vue')['default']
    HorizonList: typeof import('./src/components/HorizonList.vue')['default']
    LoadImage: typeof import('./src/components/LoadImage.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    PhotoCard: typeof import('./src/components/card/PhotoCard.vue')['default']
    PlaylistCard: typeof import('./src/components/card/PlaylistCard.vue')['default']
    PositionBackTop: typeof import('./src/components/PositionBackTop.vue')['default']
    ResponsiveGrid: typeof import('./src/components/ResponsiveGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimplePagination: typeof import('./src/components/SimplePagination.vue')['default']
    SongCard: typeof import('./src/components/card/SongCard.vue')['default']
    VanBadge: typeof import('vant/es')['Badge']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanFloatingPanel: typeof import('vant/es')['FloatingPanel']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPagination: typeof import('vant/es')['Pagination']
    VanPopover: typeof import('vant/es')['Popover']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanSearch: typeof import('vant/es')['Search']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanSkeleton: typeof import('vant/es')['Skeleton']
    VanSkeletonImage: typeof import('vant/es')['SkeletonImage']
    VanSlider: typeof import('vant/es')['Slider']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
