[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-fetch",
  "allow-fetch-send",
  "allow-fetch-cancel",
  "allow-fetch-read-body",
  "allow-fetch-and-save",
]

[allow]
http = ['http://*']
https = ['https://*']
