[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-get-m3u8-url",
  "allow-get-proxy-url",
  "allow-start-cast-proxy-server",
  "allow-stop-cast-proxy-server",
  "allow-get-cast-m3u8-url",
  "allow-get-cast-proxy-url",
]

[allow]
http = ['http://*']
https = ['https://*']
